version: "3.8"
services: 
    kusama-node: 
        image: parity/polkadot:latest
        volumes: 
            - kusama-node:/polkadot
        container_name: Kusama_Node
        command: '--name "CrommVardekNode" --chain kusama --unsafe-ws-external --rpc-cors=all --wasm-execution Compiled'
        ports:
            - "30333:30333"
    sidecar:
        image: parity/substrate-api-sidecar:latest
        container_name: Kusama_sidecar
        ports:
            - "127.0.1.1:8080:8080"
        environment:
            SAS_SUBSTRATE_WS_URL: ws://kusama-node:9944

volumes:
  kusama-node:
    external: true    