version: "3.8"
services: 
    kusama-node: 
        image: parity/polkadot:latest
        volumes:
            - kusama-node:/data
        container_name: Kusama_Node
        command: '--name "CrommVardekNode" --chain kusama --unsafe-ws-external --rpc-cors=all --base-path /data/polkadot --wasm-execution Compiled'
        ports:
            - "127.0.1.1:30333:30333"
    sidecar:
        image: parity/substrate-api-sidecar:latest
        container_name: Kusama_sidecar
        ports:
            - "127.0.1.1:8080:8080"
        environment:
            SAS_SUBSTRATE_WS_URL: wss://kusama-rpc.polkadot.io

volumes:
  kusama-node:
    external: true    