version: "3.8"
services: 
    kusama-node: 
        image: parity/polkadot:latest
        volumes:
            - kusama-node:/data
        container_name: kusama-node
        command: '--name "CrommVardekNode" --chain kusama --unsafe-ws-external --pruning archive --rpc-cors=all --base-path /data/polkadot --wasm-execution Compiled'
        ports:
            - "127.0.1.1:30333:30333"
        networks:
            - kusama
    sidecar:
        image: parity/substrate-api-sidecar:latest
        container_name: kusama-sidecar
        read_only: true
        ports:
            - "127.0.1.10:8080:8080"
        networks:
            - kusama
        environment:
            SAS_SUBSTRATE_WS_URL: wss://kusama-rpc.polkadot.io

networks:
    kusama:
        external: true

volumes:
  kusama-node:
    external: true