version: "3.8"
services: 
    polkadot-node: 
        image: parity/polkadot:latest
        volumes: 
            - polkadot-node:/polkadot
        container_name: Polkadot_Node
        command: '--name "CrommVardekNode" --chain polkadot --unsafe-ws-external --rpc-cors=all --wasm-execution Compiled'
        ports:
            - "30333:30333"
    sidecar:
        image: parity/substrate-api-sidecar:latest
        ports:
            - "8080:8080"
        environment:
            SAS_SUBSTRATE_WS_URL: ws://polkadot-node:9944

volumes:
  polkadot-node:
    external: true    