version: "3.8"
services: 
    polkadot-node: 
        image: parity/polkadot:latest
        volumes: 
            - polkadot-node:/data
        container_name: polkadot-Node
        command: '--name "CrommVardekNode" --chain polkadot --unsafe-ws-external --pruning archive --base-path /data/polkadot --rpc-cors=all --wasm-execution Compiled'
        ports:
            - "127.0.0.1:30333:30333"
        networks:
            - polkadot
    sidecar:
        image: parity/substrate-api-sidecar:latest
        container_name: polkadot-sidecar
        ports:
            - "127.0.0.10:8080:8080"
        networks:
            - polkadot
        environment:
            SAS_SUBSTRATE_WS_URL: wss://rpc.polkadot.io

volumes:
  polkadot-node:
    external: true

networks:
    polkadot:
        external: true